spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #healthCheckPath: ${management.contextPath}/health
        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: consul-consumer
        enabled: true
      enabled: true
  application:
    name: consul-consumer
server:
  port: 8503